[phases.setup]
nixPkgs = ["gcc", "postgresql", "python39", "python39Packages.pip"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "python manage.py migrate && gunicorn teacher.wsgi:application --bind 0.0.0.0:$PORT"