# Generated by Django 2.2.19 on 2024-07-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('full_text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Памятка',
                'verbose_name_plural': 'Памятки',
            },
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Запись для учеников', 'verbose_name_plural': 'Записи для учеников'},
        ),
    ]
