# Generated by Django 2.2.19 on 2024-07-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20240706_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
