# Generated by Django 2.2.19 on 2024-07-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_memos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('full_text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Совет и рекомендация для учеников',
                'verbose_name_plural': 'Советы и рекомендации для учеников',
            },
        ),
    ]
