# Generated by Django 4.2.1 on 2025-04-28 16:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_articles_id_alter_memos_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memos',
            name='date',
        ),
        migrations.RemoveField(
            model_name='memos',
            name='full_text',
        ),
        migrations.AddField(
            model_name='memos',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
