# Generated by Django 4.2.1 on 2025-04-30 05:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст с форматированием')),
            ],
            options={
                'verbose_name': 'Совет и рекомендация',
                'verbose_name_plural': 'Советы и рекомендации',
            },
        ),
        migrations.CreateModel(
            name='Files_for_Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='books/%Y-%m-%d/')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='parents.recommendations')),
            ],
            options={
                'verbose_name': 'Материал к разделу советы и рекомендации',
                'verbose_name_plural': 'Материалы к разделу советы и рекомендации',
            },
        ),
    ]
