# Generated by Django 4.2.1 on 2025-04-30 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_alter_answer_answer_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_choice',
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='parents.question'),
        ),
    ]
