# Generated by Django 4.2.1 on 2025-04-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0006_remove_answer_answer_choice_answer_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.question')),
            ],
        ),
    ]
