# Generated by Django 4.2.1 on 2025-04-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0008_testnew_questionnew_answeroptionnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
