# Generated by Django 4.2.1 on 2025-04-30 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0009_remove_useranswer_answer_remove_useranswer_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('result_text', models.TextField(verbose_name='Результат')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='parents.testnew')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
            },
        ),
    ]
