# Generated by Django 2.2.19 on 2024-07-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, unique=True, verbose_name='Текстовый документ')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.ManyToManyField(to='workshop.Documents', verbose_name='Текстовые документы')),
            ],
            options={
                'verbose_name': 'Материал к разделу внеурочная деятельность',
                'verbose_name_plural': 'Материалы к разделу внеурочная деятельность',
            },
        ),
    ]
