# Generated by Django 2.2.19 on 2024-07-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='word',
            field=models.FileField(upload_to='books/%Y-%m-%d/'),
        ),
    ]
