# Generated by Django 2.2.19 on 2024-07-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20240717_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='text',
        ),
        migrations.AddField(
            model_name='activities',
            name='new_text',
            field=models.FileField(default='0000000', upload_to='books/%Y-%m-%d/'),
        ),
    ]
