# Generated by Django 2.2.19 on 2024-07-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_auto_20240717_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='new_text',
        ),
        migrations.AddField(
            model_name='activities',
            name='text',
            field=models.ManyToManyField(to='workshop.Documents', verbose_name='Текстовые документы'),
        ),
    ]
