# Generated by Django 2.2.19 on 2024-07-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_auto_20240717_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='title',
            field=models.CharField(default='name', max_length=50, verbose_name='Название'),
        ),
    ]
