# Generated by Django 4.2.1 on 2025-04-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_documents_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='text',
            field=models.ManyToManyField(blank=True, null=True, related_name='Acti', to='workshop.documents', verbose_name='Текстовые документы'),
        ),
    ]
