# Generated by Django 4.2.1 on 2025-04-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_alter_activities_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents_for_measuring_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='name', max_length=50, verbose_name='Название')),
                ('document', models.FileField(upload_to='books/%Y-%m-%d/')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='Measuring_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('materials', models.ManyToManyField(blank=True, null=True, related_name='Measuring', to='workshop.documents_for_measuring_materials', verbose_name='Материалы')),
            ],
            options={
                'verbose_name': 'Материал к разделу измерительные материалы',
                'verbose_name_plural': 'Материалы к разделу измерительные материалы',
            },
        ),
    ]
