# Generated by Django 4.2.1 on 2025-04-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_lessons_files_for_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='files_for_lesson',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
