# Generated by Django 4.2.1 on 2025-04-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_files_for_lesson_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='archive',
            field=models.FileField(blank=True, null=True, upload_to='books/%Y-%m-%d/', verbose_name='Архив материалов'),
        ),
    ]
