# Generated by Django 4.2.1 on 2025-04-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_remove_lessons_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='description',
        ),
        migrations.AddField(
            model_name='lessons',
            name='class_number',
            field=models.TextField(blank=True, null=True, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='equipment',
            field=models.TextField(blank=True, null=True, verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='goal',
            field=models.TextField(blank=True, null=True, verbose_name='Цель'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='lesson_type',
            field=models.TextField(blank=True, null=True, verbose_name='Тип урока'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='program',
            field=models.TextField(blank=True, null=True, verbose_name='Программа'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='subject',
            field=models.TextField(blank=True, null=True, verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='tasks',
            field=models.TextField(blank=True, null=True, verbose_name='Задачи'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='topic',
            field=models.TextField(blank=True, null=True, verbose_name='Тема'),
        ),
    ]
