# Generated by Django 4.2.1 on 2025-04-28 16:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0013_remove_lessons_description_lessons_class_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст с форматированием'),
        ),
    ]
