# Generated by Django 4.2.1 on 2025-04-30 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0015_documents_for_measuring_materials_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents_for_measuring_materials',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documents_for_measuring_materials',
            name='title',
        ),
        migrations.RemoveField(
            model_name='measuring_materials',
            name='materials',
        ),
    ]
