# Generated by Django 4.2.1 on 2025-04-30 04:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0017_documents_activity_documents_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст с форматированием'),
        ),
    ]
