# Generated by Django 4.2.1 on 2025-04-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0018_activities_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='text',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='title',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='word',
        ),
    ]
